### ISSUE TITLE
Documentar o dicionário de dados

### ISSUE THREAD

**Issue by pauloFrancisconi** [Joao-AugustoPF/sistema-de-gestao-de-estacionamento#12]
Documentar o dicionário de dados e inserir os indices

**Comment by rhyanorben** [comment]
[dicionarioFuncionarios.xlsx](https://github.com/user-attachments/files/15795643/dicionarioFuncionarios.xlsx)
[dicionarioHistoricoManutencao.xlsx](https://github.com/user-attachments/files/15795644/dicionarioHistoricoManutencao.xlsx)
[dicionarioMovimentacoes.xlsx](https://github.com/user-attachments/files/15795645/dicionarioMovimentacoes.xlsx)
[dicionarioPagamentos.xlsx](https://github.com/user-attachments/files/15795647/dicionarioPagamentos.xlsx)
[dicionarioPrecos.xlsx](https://github.com/user-attachments/files/15795648/dicionarioPrecos.xlsx)
[dicionarioReservas.xlsx](https://github.com/user-attachments/files/15795649/dicionarioReservas.xlsx)
[dicionarioVagas.xlsx](https://github.com/user-attachments/files/15795650/dicionarioVagas.xlsx)
[dicionarioVeiculos.xlsx](https://github.com/user-attachments/files/15795651/dicionarioVeiculos.xlsx)

Preenchido atributos do primeiro diagrama feito, será revisado e alterado ainda conforme mudanças.

**Comment by Wesley-SM** [comment]
Necessita atualizar para esse modelo, para que eu possa atualizar o relatório, quando for fazer, eu posso te ajudar só chamar.
![DIAGRAMA-BANCO-DE-DADOS](https://github.com/Joao-AugustoPF/sistema-de-gestao-de-estacionamento/assets/160548095/d695b7a4-5593-4ea3-bdc8-9c4253287655)

**Comment by rhyanorben** [comment]
## Finalizado documentação das tabelas.

[dicionarioFuncionarios.xlsx](https://github.com/user-attachments/files/15957235/dicionarioFuncionarios.xlsx)
[dicionarioMovimentacoes.xlsx](https://github.com/user-attachments/files/15957237/dicionarioMovimentacoes.xlsx)
[dicionarioPagamentos.xlsx](https://github.com/user-attachments/files/15957238/dicionarioPagamentos.xlsx)
[dicionarioPermissoes.xlsx](https://github.com/user-attachments/files/15957239/dicionarioPermissoes.xlsx)
[dicionarioTarifas.xlsx](https://github.com/user-attachments/files/15957240/dicionarioTarifas.xlsx)
[dicionarioTipoVaga.xlsx](https://github.com/user-attachments/files/15957241/dicionarioTipoVaga.xlsx)
[dicionarioVagas.xlsx](https://github.com/user-attachments/files/15957242/dicionarioVagas.xlsx)
[dicionarioVeiculos.xlsx](https://github.com/user-attachments/files/15957243/dicionarioVeiculos.xlsx)
