### ISSUE TITLE
Criar 4 Perguntas de negócio 

### ISSUE THREAD

**Issue by Wesley-SM** [Joao-AugustoPF/sistema-de-gestao-de-estacionamento#17]
Criar 4 Perguntas de negócio  e responder com SQL INDEXADO.

Perguntas Fortes e criativas

**Comment by igrocha** [comment]
Ideias de perguntas
Como será feita a gestão das vagas disponíveis?
Que tipo de relatórios e análises serão disponibilizados para os administradores?
Como será gerido o suporte ao cliente?
Como os usuários poderão relatar problemas ou solicitar assistência?
Qual é a taxa de ocupação média do estacionamento?
Quais são os horários de pico de utilização?
Há padrões sazonais de uso?

**Comment by pauloFrancisconi** [comment]
as perguntas ficaram assim: 
1. Quantos veículos estão estacionados no momento?
2. Qual é a receita total por tipo de veículo até o momento?
3. Qual é a média de receita por pagamento realizado?
4. Qual é a duração média por tipo de veículo?

Os scripts SQL ja foram commitados no github, encerrando a issue.
