### ISSUE TITLE
Preencher os documentos de documentação do projeto

### ISSUE THREAD

**Issue by Realdo-Justino** [Joao-AugustoPF/sistema-de-gestao-de-estacionamento#4]
Preencher os documentos encontrados na pasta [documentos](https://github.com/Joao-AugustoPF/sistema-de-gestao-de-estacionamento/tree/main/Documentos) para documentação

**Comment by Wesley-SM** [comment]
Atualizado, está faltando o dicionário de dados ser atualizado 

[https://github.com/Joao-AugustoPF/sistema-de-gestao-de-estacionamento/tree/main/relatorio](url)

**Comment by rhyanorben** [comment]
Dicionário de dados atualizado e inserido as tabelas no relatório.
