### ISSUE TITLE
Escolher Nome Para o Projeto

### ISSUE THREAD

**Issue by Realdo-Justino** [Joao-AugustoPF/sistema-de-gestao-de-estacionamento#6]
Minhas Sugestões:
- Parkify
- SpotEase
- LotKepper
- GarageGenie

**Comment by Wesley-SM** [comment]
- voto no GarageGenie

**Comment by igrocha** [comment]
Minhas Sugestões:
Stop Car
Ponto Park
Viatown
Cri Park

**Comment by Realdo-Justino** [comment]
Foi Decido em ParkGenie

**Comment by Realdo-Justino** [comment]
Foi Decido em ParkGenie
