### ISSUE TITLE
Criar o diagrama do modelo físico

### ISSUE THREAD

**Issue by Realdo-Justino** [Joao-AugustoPF/sistema-de-gestao-de-estacionamento#7]
Mínimo 8 itens principais

**Comment by pauloFrancisconi** [comment]
Boa noite, 
Esse diagrama seria uma boa solução para essa tarefa?
Se sim, podemos iniciar tarefa [https://github.com/Joao-AugustoPF/sistema-de-gestao-de-estacionamento/issues/9](url)
![image](https://github.com/Joao-AugustoPF/sistema-de-gestao-de-estacionamento/assets/128430344/e18438bd-21a5-4b42-97ca-34cd91c0d6dc)

**Comment by pauloFrancisconi** [comment]
Ultimo diagrama criado e atualizado conforme alterações no banco de dados, ele está disposto nos arquivos desse repositório.
