### ISSUE TITLE
Criar O Banco De Dados

### ISSUE THREAD

**Issue by Realdo-Justino** [Joao-AugustoPF/sistema-de-gestao-de-estacionamento#8]
Sugestões:
- SqlLite
- PostgreSQL
- MySQL Workbench

**Comment by rhyanorben** [comment]
Utilizado MySQL na criação do banco de dados.

**Comment by rhyanorben** [comment]
Tabela Funcionarios:

- Coluna permissao_id deve ser NOT NULL.
- Tabela ficou sem index

Tabela Movimentações:

- Coluna movimentacao_id deve ser NOT NULL
- Data_pagamento deve ser NOT NULL

Tabela Vagas:

- Sugestão: Adicionar coluna andar
- Alterar o tipo de dado da coluna "disponivel" para boolean e definir NOT NULL

Vou analisar o restante das tabelas ainda

**Comment by pauloFrancisconi** [comment]
Banco de dados criado com MySQL utilizando Nodejs para a criação. Lembrando que o banco precisa ser criado no momento da apresentação do Projeto
